select *
from "Customer" limit 20

--Q1. What is the total revenue generated by male vs female?
select gender, sum(purchase_amount) as revenue
from "Customer"
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from "Customer"
where discount_applied = 'Yes' AND purchase_amount >= (select avg(purchase_amount) from "Customer")

--Q3. Which are the top 5 products with the highest review rating?
select item_purchased, Round(avg(review_rating::numeric),2) as "average product rating"
from "Customer" 
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average purchase amounts between standard and express shipping.
select shipping_type, round(avg(purchase_amount),2)
from "Customer" 
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend & total revenue between subscribers & non-subscribers.
select subscription_status, 
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_spend,
round(sum(purchase_amount),2) as total_revenue
from "Customer"
group by subscription_status
order by average_spend, total_revenue desc

--Q6. Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
round(100*sum(case when discount_applied = 'Yes' THEN 1 Else 0 End)/Count(*),2) as discount_rate
from "Customer"
group by item_purchased
order by discount_rate desc
limit 5

--Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.
With customer_type as
(
select customer_id, previous_purchases,
case 
when previous_purchases = 1 Then 'New'
when previous_purchases between 1 and 10 Then 'Returning'
else 'Loyal'
End as customer_segment
from "Customer"
)

select customer_segment, count(*) as "No. of Customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
with item_count as (
select category, item_purchased,
count(customer_id) as total_orders,
Row_number() over(partition by category order by count(customer_id) desc) as item_rank
from "Customer"
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_count
where item_rank <= 3

--Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from "Customer"
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as revenue_contribution
from "Customer"
group by age_group
order by revenue_contribution desc